#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
\getenv app_password APP_DB_PASSWORD
\getenv owner_password OWNER_DB_PASSWORD
CREATE ROLE hr_owner LOGIN PASSWORD :'owner_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE hr_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER DATABASE hr_platform OWNER TO hr_owner;
GRANT USAGE, CREATE ON SCHEMA public TO hr_owner;
GRANT USAGE ON SCHEMA public TO hr_app;
SQL
