import {test,expect} from '@playwright/test'
import {TOTP,Secret} from 'otpauth'
test('real cookie login, privileged MFA enrollment and company scope',async({page})=>{
  const password=process.env.HR_DEMO_PASSWORD
  if(!password)throw new Error('HR_DEMO_PASSWORD is required for the synthetic fixture')
  const bad=await page.request.post('/login',{data:{email:'admin@example.test',password},headers:{Accept:'application/json'}})
  expect(bad.status()).toBe(419)
  await page.goto('/login')
  await page.getByLabel('Work email').fill('admin@example.test')
  await page.getByLabel('Password',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Your organization'})).toBeVisible()
  await page.getByLabel('Active tenant').selectOption({label:'Demo Group'})
  await expect(page.getByRole('heading',{name:'Two-factor authentication'})).toBeVisible()
  await page.getByLabel('Current password').fill(password)
  await page.getByRole('button',{name:'Set up authenticator'}).click()
  const secret=await page.locator('code.secret').innerText()
  const totp=new TOTP({secret:Secret.fromBase32(secret),digits:6,period:30,algorithm:'SHA1'})
  const enrolledCode=totp.generate()
  await page.getByLabel('Authenticator code').fill(enrolledCode)
  await page.getByRole('button',{name:'Confirm enrollment'}).click()
  await expect(page.locator('.codes li')).toHaveCount(8)
  await page.getByRole('button',{name:'Saved — sign in with MFA'}).click()
  await page.getByLabel('Work email').fill('admin@example.test')
  await page.getByLabel('Password',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Sign in',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Verify your identity'})).toBeVisible()
  // Enrollment consumed the current time-step code; wait for a new one.
  await expect.poll(()=>totp.generate(),{timeout:35000,intervals:[1000]}).not.toBe(enrolledCode)
  await page.getByLabel('Authenticator code').fill(totp.generate())
  await page.getByRole('button',{name:'Verify and continue'}).click()
  await page.getByLabel('Active tenant').selectOption({label:'Demo Group'})
  await expect(page.getByRole('heading',{name:'Demo Company A'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Demo Company B'})).toBeVisible()
  const token=await page.getByLabel('Active tenant').inputValue()
  const api=await page.request.get('/api/v1/companies',{headers:{Accept:'application/json','X-Tenant-ID':token}})
  expect(api.ok()).toBeTruthy()
  expect((await api.json()).data).toHaveLength(2)
  await page.screenshot({path:'test-results/workspace-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('heading',{name:'Demo Company A'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({path:'test-results/workspace-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  expect((await page.request.get('/api/v1/me',{headers:{Accept:'application/json'}})).status()).toBe(401)
})
